## < Problem 1 >
![problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinetics/rigid_bodies/rigid_body_parallel_axis_theorem_01.png?raw=true)

In [2]:
!wget -O attitude.py https://raw.githubusercontent.com/seoupark1/Stochastic-Control/main/src/stochastic_control/kinematics/attitude.py

--2026-07-17 11:17:55--  https://raw.githubusercontent.com/seoupark1/Stochastic-Control/main/src/stochastic_control/kinematics/attitude.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6006 (5.9K) [text/plain]
Saving to: ‘attitude.py’

attitude.py         100%[===================>]   5.87K  --.-KB/s    in 0s      

2026-07-17 11:17:55 (48.2 MB/s) - ‘attitude.py’ saved [6006/6006]



In [4]:
import numpy as np
from attitude import ea321_to_dcm, skew_symmetric

# initial values
M = 12.5
euler_angles_deg = np.array([-10, 10, 5])
euler_angles_rad = np.radians(euler_angles_deg)
Ic_B = np.array([[10, 1, -1],
                [1, 5, 1],
                [-1, 1, 8]])
dcm_bn = ea321_to_dcm(euler_angles_rad)

# change Rcp_N to Rcp_B
Rcp_N = np.array([-0.5, 0.5, 0.25])
Rcp_B = dcm_bn @ Rcp_N

def parallel_axis(Ic_B, M, Rcp_B):
    Ip_B = Ic_B + M * skew_symmetric(Rcp_B) @ np.transpose(skew_symmetric(Rcp_B))

    return Ip_B

print(parallel_axis(Ic_B, M, Rcp_B))

[[12.32125207  4.19755562 -0.15813867]
 [ 4.19755562  9.86047157  0.42847142]
 [-0.15813867  0.42847142 14.88077637]]
