## < Problem 1 >
![problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinetics/rigid_bodies/rigid_body_coordinate_transform_01.png?raw=true)

In [1]:
!git clone https://github.com/seoupark1/Stochastic-Control.git

Cloning into 'Stochastic-Control'...
remote: Enumerating objects: 545, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 545 (delta 12), reused 65 (delta 2), pack-reused 460 (from 2)
Receiving objects: 100% (545/545), 46.34 MiB | 28.60 MiB/s, done.
Resolving deltas: 100% (111/111), done.


In [4]:
import os
print(os.getcwd())

%cd Stochastic-Control

/content
/content/Stochastic-Control


In [7]:
import numpy as np
from src.stochastic_control.kinematics import rotations, attitude

# Modified Rodrigues Parameters to Direction Cosine Matrix
def MRP2C(sigma):
    dcm_BN = (np.eye(3) + (8*rotations.skew_symmetric(sigma)@rotations.skew_symmetric(sigma) - 4*(1-np.vdot(sigma,sigma))*rotations.skew_symmetric(sigma))
    / (1+np.vdot(sigma,sigma))**2)

    return dcm_BN

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
sigma_DB = np.array([0.1, 0.2, 0.3]).reshape(3,1)
dcm_DB = attitude.mrp_to_dcm(sigma_DB)

Ic_D = dcm_DB @ Ic_B @ np.transpose(dcm_DB)
print(Ic_D)

[[ 5.42779505 -1.77341012  1.37988231]
 [-1.77341012  9.27952214 -0.53047352]
 [ 1.37988231 -0.53047352  8.29268281]]


## < Problem 2 >
![problem 2](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinetics/rigid_bodies/rigid_body_coordinate_transform_02.png?raw=true)

In [9]:
import numpy as np

# Principal Inertias & Corresponding DCM
def coordinate_transform(Ic_B):
    # get eigenvalues & eigenvectors
    eig_vals, eig_vecs = np.linalg.eigh(Ic_B)

    # change eigenvalue's index
    I_min, I_med, I_max = eig_vals[0], eig_vals[1], eig_vals[2]
    eig_vals = np.array([I_max, I_med, I_min])

    # change eigenvector's index & make [FB] dcm
    v_min, v_med, v_max = eig_vecs[:, 0], eig_vecs[:, 1], eig_vecs[:, 2]
    dcm_FB = np.array([v_max, v_med, v_min])

    return eig_vals, dcm_FB

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
principalInertias = coordinate_transform(Ic_B)[0]
print(principalInertias)

[10.47419366  8.11268085  4.41312549]


## < Problem 3 >
![problem 3](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinetics/rigid_bodies/rigid_body_coordinate_transform_03.png?raw=true)

In [10]:
import numpy as np

# Principal Inertias & Corresponding DCM
def coordinate_transform(Ic_B):
    # get eigenvalues & eigenvectors
    eig_vals, eig_vecs = np.linalg.eigh(Ic_B)

    # change eigenvalue's index
    I_min, I_med, I_max = eig_vals[0], eig_vals[1], eig_vals[2]
    eig_vals = np.array([I_max, I_med, I_min])

    # change eigenvector's index & make [FB] dcm
    v_min, v_med, v_max = eig_vecs[:, 0], eig_vecs[:, 1], eig_vecs[:, 2]
    dcm_FB = np.array([v_max, v_med, v_min])

    # if dcm_FB's det = -1, we have to change it to right-handed
    if np.linalg.det(dcm_FB) < 0:
        dcm_FB[2, :] = -dcm_FB[2, :]

    return eig_vals, dcm_FB

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
FB = coordinate_transform(Ic_B)[1]
print(FB)

[[ 0.93616416  0.11001782 -0.33390528]
 [ 0.27260861  0.37256363  0.88706307]
 [ 0.22199371 -0.92146211  0.31878891]]
