## < Problem 1 >
![problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/devenports_q_method/devenports_q_method_01.png?raw=true)

In [ ]:
import numpy as np

def q_method(v1_est, v1_true, v2_est, v2_true):
    # normalization
    v1_est = v1_est / np.linalg.norm(v1_est)
    v1_true = v1_true / np.linalg.norm(v1_true)
    v2_est = v2_est / np.linalg.norm(v2_est)
    v2_true = v2_true / np.linalg.norm(v2_true)

    # weight
    w1 = 0.5
    w2 = 0.5

    # Devenport's q-method
    B = w1 * v1_est @ np.transpose(v1_true) + w2 * v2_est @ np.transpose(v2_true)
    Z = np.array([B[1,2] - B[2,1], B[2,0] - B[0,2], B[0,1] - B[1,0]]).reshape(3,1)
    sigma = np.trace(B)
    S = B + np.transpose(B)
    K = np.block([[sigma, np.transpose(Z)], [Z, S - sigma * np.eye(3)]])

    # finding K's largest eigenvalues, eigenvectors
    eigenvalues, eigenvectors = np.linalg.eigh(K)
    eigenvalue = eigenvalues[3]
    eigenvector = eigenvectors[:, 3]

    return eigenvector

def EP2C(EP):
    B0 = EP[0]
    B1 = EP[1]
    B2 = EP[2]
    B3 = EP[3]

    C = np.array([[B0**2 + B1**2 - B2**2 - B3**2, 2*(B1*B2 + B0*B3), 2*(B1*B3 - B0*B2)],
                  [2*(B1*B2 - B0*B3), B0**2 - B1**2 + B2**2 - B3**2, 2*(B2*B3 + B0*B1)],
                  [2*(B1*B3 + B0*B2), 2*(B2*B3 - B0*B1), B0**2 - B1**2 - B2**2 + B3**2]])
    return C

v1_est = np.array([0.8273, 0.5541, -0.0920]).reshape(3,1)
v2_est = np.array([-0.8285, 0.5522, -0.0955]).reshape(3,1)
v1_true = np.array([-0.1517, -0.9669, 0.2050]).reshape(3,1)
v2_true = np.array([-0.8393, 0.4494, -0.3044]).reshape(3,1)
EP_BbarN = q_method(v1_est, v1_true, v2_est, v2_true)
dcm_BbarN = EP2C(EP_BbarN)
print(dcm_BbarN)

[[ 0.41593638 -0.85489353  0.31008705]
 [-0.83375667 -0.49463677 -0.24532483]
 [ 0.36310707 -0.15649762 -0.91851062]]
