## < Problem 1 >
![problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/triad_method/triad_method_01.png?raw=true)

In [ ]:
import numpy as np

def tilde(v):
    result = np.array([[0, -v[2], v[1]],
                       [v[2], 0, -v[0]],
                       [-v[1], v[0], 0]])

    return result

# set sensor v1 is more accurate than sensor v2
def TRIAD_method(v1_B, v2_B, v1_N, v2_N):

    # normalization
    v1_B = v1_B / np.linalg.norm(v1_B)
    v2_B = v2_B / np.linalg.norm(v2_B)
    v1_N = v1_N / np.linalg.norm(v1_N)
    v2_N = v2_N / np.linalg.norm(v2_N)

    # define t
    t1_B = v1_B
    t2_B = tilde(v1_B) @ v2_B / np.linalg.norm(tilde(v1_B) @ v2_B)
    t3_B = tilde(t1_B) @ t2_B

    t1_N = v1_N
    t2_N = tilde(v1_N) @ v2_N / np.linalg.norm(tilde(v1_N) @ v2_N)
    t3_N = tilde(t1_N) @ t2_N

    # get dcm_estimate
    dcm_BbarT = np.column_stack((t1_B, t2_B, t3_B))
    dcm_NT = np.column_stack((t1_N, t2_N, t3_N))
    dcm_BbarN = dcm_BbarT @ np.transpose(dcm_NT)

    return dcm_BbarN


v1_B = np.array([0.8273, 0.5541, -0.0920])
v2_B = np.array([-0.8285, 0.5522, -0.0955])
v1_N = np.array([-0.1517, -0.9669, 0.2050])
v2_N = np.array([-0.8393, 0.4494, -0.3044])
print(TRIAD_method(v1_B, v2_B, v1_N, v2_N))


[[ 0.41555875 -0.85509088  0.31004921]
 [-0.83393237 -0.49427603 -0.24545471]
 [ 0.36313597 -0.15655922 -0.91848869]]


## < Problem 2 >
![problem 2](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/triad_method/triad_method_02.png?raw=true)

In [ ]:
import numpy as np

def C2PRV(dcm_estimate, dcm_true):
    # error = dcm_BbarB
    dcm_error = dcm_estimate @ np.transpose(dcm_true)

    # principal angle 구하기
    PRV_angle = np.arccos((np.trace(dcm_error) - 1) / 2)
    PRV_angle = np.degrees(PRV_angle)

    return PRV_angle

dcm_BbarN = np.array([[0.969846, 0.17101, 0.173648], [-0.200706, 0.96461, 0.17101], [-0.138258, -0.200706, 0.969846]])
dcm_BN = np.array([[0.963592, 0.187303, 0.190809], [-0.223042, 0.956645, 0.187303], [-0.147454, -0.223042, 0.963592]])
print(C2PRV(dcm_BbarN, dcm_BN))


1.8349476067250545
