## < Problem 1 >
![problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/classical_rodrigues_parameters/crp_addition_01.png?raw=true)

In [ ]:
import numpy as np

def crp_to_dcm(q1, q2, q3):
    # defining CRPs
    q = np.array([q1, q2, q3]).transpose()

    # defining dcm
    row1 = np.array([1+q1**2-q2**2-q3**2, 2*(q1*q2+q3), 2*(q1*q3-q2)])
    row2 = np.array([2*(q2*q1-q3), 1-q1**2+q2**2-q3**2, 2*(q2*q3+q1)])
    row3 = np.array([2*(q3*q1+q2), 2*(q3*q2-q1), 1-q1**2-q2**2+q3**2])
    dcm_C = np.array([row1, row2, row3]) / (1 + q.transpose()@q)

    return dcm_C

print(crp_to_dcm(0.1, 0.2, 0.3))


[[ 0.77192982  0.56140351 -0.29824561]
 [-0.49122807  0.8245614   0.28070175]
 [ 0.40350877 -0.07017544  0.9122807 ]]


## < Problem 2 >
![problem 2](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/classical_rodrigues_parameters/crp_addition_02.png?raw=true)

In [ ]:
import numpy as np

def dcm_to_crp(dcm): # dcm은 3X3 dcm
    # defining zeta
    zeta = np.sqrt(1 + np.trace(dcm))

    # defining CRPs
    q = np.array([dcm[1,2] - dcm[2,1], dcm[2,0]-dcm[0,2], dcm[0,1] - dcm[1,0]]).transpose() / zeta**2

    return q

value = np.array([[0.333333, -0.666667, 0.666667], [0.871795, 0.487179, 0.0512821], [-0.358974, 0.564103, 0.74359]])
print(dcm_to_crp(value))

[-0.2000002  -0.40000008 -0.60000031]


## < Problem 3 >
![problem 3](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/classical_rodrigues_parameters/crp_addition_03.png?raw=true)

In [ ]:
def BN_to_NB(*q):
    crp = -np.array(*q)

    return crp

value = [0.1, 0.2, 0.3]
print(BN_to_NB(value))

[-0.1 -0.2 -0.3]


## < Problem 4 >
![problem 4](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/classical_rodrigues_parameters/crp_addition_04.png?raw=true)

In [ ]:
# dcm_BF = dcm_BN * dcm_NF
import numpy as np

def dcm_addition(q_dot2, q_dot1):
    q = (q_dot2 + q_dot1 - np.cross(q_dot2, q_dot1)) / (1 - np.dot(q_dot2, q_dot1))

    return q

q_FN = np.array([0.1, 0.2, 0.3])
q_BN = np.array([-0.3, 0.3, 0.1])
print(dcm_addition(q_BN, -q_FN))

[-0.31132075  0.18867925 -0.27358491]
