## < Problem 1 >
![Problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/directional_cosine_matrices/directional_cosine_matrices_01.png?raw=true)

In [ ]:
import numpy as np

def result():
    # dcm_BN
    b1 = np.array([1, 2, -2]) / 3
    b2 = np.array([0, 1, 1]) / np.sqrt(2)
    b3 = np.array([4, -1, 1]) / (3*np.sqrt(2))
    b = np.array([b1, b2, b3])

    # dcm_FN
    f1 = np.array([3, -2, np.sqrt(3)]) / 4
    f2 = np.array([-1, 0, np.sqrt(3)]) / 2
    f3 = np.array([np.sqrt(3), 2*np.sqrt(3), 1]) / -4
    f = np.array([f1, f2, f3])

    # dcm_BF
    BF = b @ f.transpose()

    return BF


print(result())

[[-0.37200847 -0.74401694 -0.55502117]
 [-0.04736717  0.61237244 -0.78914913]
 [ 0.92701998 -0.26728038 -0.26304971]]


---
## < Problem 2 >
![Problem 2](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/directional_cosine_matrices/directional_cosine_matrices_02.png?raw=true)

In [ ]:
import numpy as np

def result1():
    # dcm_BN
    b1 = np.array([1, 2, -2]) / 3
    b2 = np.array([0, 1, 1]) / np.sqrt(2)
    b3 = np.array([4, -1, 1]) / (3*np.sqrt(2))
    b = np.array([b1, b2, b3])
    BN = b

    return BN


print(result1())

[[ 0.33333333  0.66666667 -0.66666667]
 [ 0.          0.70710678  0.70710678]
 [ 0.94280904 -0.23570226  0.23570226]]
