## < Problem 1 >
![problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/modified_rodrigues_parameters/mrp_addition_subtraction_01.png?raw=true)

In [ ]:
import numpy as np

def MRP_BN_to_NB(v):
    v = np.array(v)
    mrp = -v
    return mrp

print(MRP_BN_to_NB([0.2, 0.2, -0.1]))

[-0.2 -0.2  0.1]


## < Problem 2 >
![problem 2](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/modified_rodrigues_parameters/mrp_addition_subtraction_02.png?raw=true)

In [ ]:
import numpy as np
import math

# v2 @ v1
def MRP_addition(v2,v1):
    v1 = np.array(v1)
    v2 = np.array(v2)

    # considering singularity
    denominator = 1 + np.dot(v1,v1)*np.dot(v2,v2) - 2*np.dot(v1, v2)
    # shadow set 치환 기준을 임의로 0.5로 잡음
    if abs(denominator) < 0.5:
        v1 = -v1/np.dot(v1,v1)

    numerator = (1-np.dot(v1,v1))*v2 + (1-np.dot(v2,v2))*v1 - 2*np.cross(v2,v1)
    denominator = 1 + np.dot(v1,v1)*np.dot(v2,v2) - 2*np.dot(v1, v2)
    MRP = numerator / denominator

    # shortest path
    norm = math.sqrt(np.dot(MRP, MRP))
    if norm > 1:
        shadow_set = -MRP/np.dot(MRP, MRP)
        MRP = shadow_set

    return MRP


v1 = [0.1, 0.2, 0.3]
v2 = [-0.1, 0.3, 0.1]
print(MRP_addition(v2, v1))


[-0.16015899  0.41617957  0.52957681]


## < Problem 3 >
![problem 3](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/modified_rodrigues_parameters/mrp_addition_subtraction_03.png?raw=true)

In [ ]:
import numpy as np
import math

# sigma_RN을 sigma_NR로 치환해서 sigma_BR을 구한다
# v2 @ v1(-sigma)
def MRP_subtraction(v2, v1):
    v1 = -np.array(v1)
    v2 = np.array(v2)

    # considering singularity
    denominator = 1 + np.dot(v1,v1)*np.dot(v2,v2) - 2*np.dot(v1, v2)
    # shadow set 치환 기준을 임의로 1로 잡음
    if abs(denominator) < 1:
        v1 = -v1/np.dot(v1,v1)

    numerator = (1-np.dot(v1,v1))*v2 + (1-np.dot(v2,v2))*v1 - 2*np.cross(v2,v1)
    denominator = 1 + np.dot(v1,v1)*np.dot(v2,v2) - 2*np.dot(v1, v2)
    MRP = numerator / denominator

    # shortest path
    norm = math.sqrt(np.dot(MRP, MRP))
    if abs(norm) >= 1:
        shadow_set = -MRP/np.dot(MRP, MRP)
        MRP = shadow_set

    return MRP

v1 = [0.5, 0.3, 0.1]
v2 = [0.1, 0.2, 0.3]
print(MRP_subtraction(v2, v1))

[-0.37998495  0.11437171 -0.02332581]
