## < Problem 1 >
![problem 1](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/modified_rodrigues_parameters/mrp_dcm_relation_01.png?raw=true)

In [ ]:
import numpy as np

def tilde(v):
    # 아래처럼 row 따로 만드는 것보다 하나의 array에 한번에 표현하는게 좋다고 함.
    row1 = np.array([0, -v[2], v[1]])
    row2 = np.array([v[2], 0, -v[0]])
    row3 = np.array([-v[1], v[0], 0])
    result = np.array([row1, row2, row3])

    return result


def MRPs_to_DCM(v):
    # np.dot(v, v) = v의 norm square
    dcm = np.eye(3) + (8*tilde(v)@tilde(v) - 4*(1-np.dot(v, v))*tilde(v)) / (1 + np.dot(v, v))**2

    return dcm

print(MRPs_to_DCM([0.1, 0.2, 0.3]))

[[ 0.19975377  0.91720529 -0.34472145]
 [-0.67097568  0.38442598  0.63404124]
 [ 0.71406587  0.10464758  0.69221299]]


## < Problem 2 >
![problem 2](https://github.com/seoupark1/Stochastic-Control/blob/main/assets/images/kinematics/modified_rodrigues_parameters/mrp_dcm_relation_02.png?raw=true)

In [ ]:
import numpy as np
import math

def DCM_to_MRPs(v):
    zeta = math.sqrt(1 + np.trace(v))
    # 대괄호 남발을 막기 위해 .reshape(3,1) 활용
    MRPs = np.array([v[1][2] - v[2][1], v[2][0] - v[0][2], v[0][1] - v[1][0]]).reshape(3,1) / (zeta*(zeta+2))

    return MRPs

print(DCM_to_MRPs([[0.763314, 0.0946746, -0.639053], [-0.568047, -0.372781, -0.733728], [-0.307692, 0.923077, -0.230769]]))


[[-0.49999988]
 [ 0.09999998]
 [ 0.19999983]]
